//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheGateWebSite.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Contacts = new HashSet<Contact>();
            this.Orders = new HashSet<Order>();
        }
    
        public int accountID { get; set; }
        public string accountNumber { get; set; }
        public int primaryContact { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public string website { get; set; }
        public string generalEmail { get; set; }
        public Nullable<int> address { get; set; }
        public Nullable<int> billingAddress { get; set; }
        public string accountName { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual Address Address { get; set; }
        public virtual Address BillingAddress { get; set; }
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
