//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheGateWebSite.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public Contact()
        {
            this.Accounts = new HashSet<Account>();
            this.Employees = new HashSet<Employee>();
            this.Orders = new HashSet<Order>();
        }
    
        public int contactID { get; set; }
        public Nullable<int> accountID { get; set; }
        public Nullable<System.Guid> userID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public Nullable<int> shippingAddress { get; set; }
        public Nullable<int> billingAddress { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual Account Account { get; set; }
        public virtual Address Address { get; set; }
        public virtual Address Address1 { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual aspnet_Membership aspnet_Membership { get; set; }
    }
}
