//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheGateWebSite.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public File()
        {
            this.Products = new HashSet<Product>();
        }
    
        public string ContentType { get; set; }
        public long Size { get; set; }
        public byte[] Data { get; set; }
        public int fileID { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
    }
}
