//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheGateWebSite.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderLines = new HashSet<OrderLine>();
        }
    
        public int orderID { get; set; }
        public int type { get; set; }
        public int state { get; set; }
        public int contactID { get; set; }
        public Nullable<int> accountID { get; set; }
        public System.DateTime dateMade { get; set; }
        public Nullable<System.DateTime> dateShipped { get; set; }
        public Nullable<System.DateTime> dateRecieved { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Contact Contact { get; set; }
        public virtual ICollection<OrderLine> OrderLines { get; set; }
        public virtual OrderType OrderType { get; set; }
        public virtual OrderState OrderState { get; set; }
    }
}
