//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheGateWebSite.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.OrderLines = new HashSet<OrderLine>();
        }
    
        public int productID { get; set; }
        public decimal price { get; set; }
        public int categoryID { get; set; }
        public string description { get; set; }
        public int onHand { get; set; }
        public int onOrder { get; set; }
        public string productName { get; set; }
        public Nullable<int> imageID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<OrderLine> OrderLines { get; set; }
        public virtual File File { get; set; }
    }
}
