//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheGateWebSite.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSheetLine
    {
        public int timeSheetLineID { get; set; }
        public int timeSheetID { get; set; }
        public decimal hours { get; set; }
    
        public virtual TimeSheet TimeSheet { get; set; }
    }
}
