//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheGateWebSite.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeEntry
    {
        public int timeID { get; set; }
        public System.DateTime date { get; set; }
        public decimal hours { get; set; }
        public string category { get; set; }
        public int employeeID { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
